name: createPullRequestToMaster
# on:
#   workflow_run:
#     workflows: [OnPushToBranch]
#     branches: [main]
#     types: [completed]

on:
  push:
    branches:
      - "!master"
      - "**"

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write

jobs:
  pull:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/labeler@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "pnpm"

      - run: pnpm install --no-frozen-lockfile
      - run: pnpm run lint && pnpm run build
      - name: Create Pull Request
        run: gh pr create -B master -H main --title 'Merge main into master' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
